### ISSUE TITLE
convolution and fully connected layers are miss ordered

### ISSUE THREAD

**Issue by marjanemd** [wanghan0501/tensorboard#1]
Hello Wanghan,

I just ran the code and visualized it in Tensorboard, and realized that the graphs were not showing the correct number of fully connected and convolution layers.

The reason is that in mnist.py in line 128 the conv_param, fc_param are miss ordered, according to the function make_hparam_string.

Hope this would be helpful.

**Comment by wanghan0501** [comment]
Thanks for your suggestion, actually, I have been using Pytorch instead of Tensorflow, and I think Pytorch is more friendly than Tensorflow for doing research.
